version: 0.0
os: linux
files:
- source: /
  destination: /home/ubuntu/zian.ke-test
permissions:
- object: /home/ubuntu/zian.ke-test
  owner: ubuntu
  group: ubuntu
hooks:
  BeforeInstall:
  - location: before_install.sh
    runas: ubuntu
  AfterInstall:
  - location: after_install.sh
    runas: ubuntu