version: 0.0
os: linux
files:
- source: /
  destination: /home/ubuntu/zian.ke
hooks:
  BeforeInstall:
  - location: scripts/before_install.sh
    runas: root
  ApplicationStart:
  - location: scripts/after_install.sh
    runas: root
